#echo alias_lp.sh, L 20.5.2011
alias d2u=dos2unix
alias cdr='cd /cygdrive; cd'
alias edr=muokkaa_drives
alias ip=ipconfig
alias k=kill
alias l='ls -la'
alias m=less
alias n='nano -w -T 2'
alias open=cygstart
alias p=projekti
alias r=rails
alias rt='cd /'
alias syn=synkronoi
alias synk=synkronoi
alias tl=tasklist
alias v=verkko
alias x=exit
alias y='synkronoi ssh'