alias ..='cd ..'
alias ...='cd ..; cd ..'
alias 1=singular
alias 1st='bulog -1'
alias 2nd='bulog -2'
alias +a='chmod a+rwx'
alias a="git add -A; git commit -m"
alias "a-"='chmod a-rwx'
alias a-r='chmod a-r'
alias a-w='chmod a-w'
alias a-x='chmod a-x'
alias "a+"='chmod a+rwx'
alias a+r='chmod a+r'
alias a+w='chmod a+w'
alias a+x='chmod a+x'
alias ac="git add -A; git commit -m"
alias add='git add'
alias al=alias
alias b=bundle
alias bi='bundle install'
alias biw='bundle install --without'
alias branch='git branch'
alias bu=bundle
alias bx='bundle exec'
alias c=clear
alias cd..='cd ..'
alias cdcd=cd
alias ci='git commit -m'
alias cim='git commit -m'
alias clone='git clone'
alias co='git checkout'
alias commit="git commit -m"
#alias d=diff
alias dc=cd
alias dox='LISTA=~/Documents/hakemisto.lst listalla'
alias dwl='synkronoi dwl'
alias e=echo
alias ed=muokkaa
alias egrep='egrep --color=auto' # show differences in colour
alias fgrep='fgrep --color=auto' # show differences in colour
alias +g='chmod g+rwx'
alias g=grep
alias "g-"='chmod g-rwx'
alias g-r='chmod g-r'
alias g-w='chmod g-w'
alias g-x='chmod g-x'
alias "g+"='chmod g+rwx'
alias g+r='chmod g+r'
alias g+w='chmod g+w'
alias g+x='chmod g+x'
alias gdf='git df'
alias gl='git log'
alias glog='git log --pretty=oneline'
alias gmv='git mv'
alias go+rwx='chmod go+rwx'
alias greeting=ciao
alias grep='grep --color=auto' # show differences in colour, check for darwin
alias h1='head -1'
alias h=heroku
alias h2='pwd; hakemisto; hakemisto'
alias H2='h2; ..; h2'
alias H3='h2; ..; h2; ..; h2'
alias H4='h2; ..; h2; ..; h2; ..; h2'
alias hak=hakemisto
alias hst='cat ~/.bash_history'
alias k=kill
alias k80=kaiku80
alias k9='kill -9'
alias ker=kerain
#alias levy='df -h'
alias l3='ls -la|less'
alias llg='ls -la|grep'
alias lll='ls -la|less'
alias logs='git log --pretty=oneline'
alias m=less
alias md=mkdir
alias merge='git merge'
alias mig='rails db:migrate'
alias migr='rails db:migrate'
alias migrate='rails db:migrate'
alias more=less
alias n=nano
alias n2='nano -w -T 2'
alias +o='chmod o+rwx'
alias "o-"='chmod o-rwx'
alias o-r='chmod o-r'
alias o-w='chmod o-w'
alias o-x='chmod o-x'
alias "o+"='chmod o+rwx'
alias o+r='chmod o+r'
alias o+w='chmod o+w'
alias o+x='chmod o+x'
alias "og-"='chmod og-rwx'
alias og-r='chmod og-r'
alias og-rwx='chmod og-rwx'
alias og+rwx='chmod og+rwx'
alias origin='git remote -v|grep origin'
alias og+rwx='chmod og-rwx'
alias ole=olemassa
alias P=projekti-func
alias p=projekti-func
alias psf='ps fu'
alias pul='git pull'
alias pull='git pull'
alias psh='git push'
alias push='git push'
alias py2=python
alias py3=python3
alias +r='chmod +r'
alias r=rails
alias "r-"='chmod a-r'
alias "r+"='chmod a+r'
alias rail=rails
alias rb=rbenv
alias rc=rubocop
alias rd=rmdir
alias remote='git remote'
alias reset='rails db:migrate:reset'
alias rmd='rm .DS_Store'
alias rollback='rails db:rollback'
alias routes='rails routes'
alias rl='screen -list'
alias rs='rails server'
alias rt='rails test'
alias ru=screen
alias ruu=screen
alias rv='git remote -v'
alias s3=sqlite3
alias sans='bundle install --without'
alias seed='rails db:seed'
alias show='git show'
alias server='rails server'
alias srv='rails server'
alias st='if [ -d .git ]; then git status; else if [ -d ../.git ]; then git status; else if [ -d ../../.git ]; then git status; fi; fi; fi'
alias sy=synkronoi
alias syn='synkronoi syn'
alias t=touch
alias t1='tail -1'
alias tst='rails test'
alias +u='chmod u+rwx'
alias "u-"='chmod u-rwx'
alias u-r='chmod u-r'
alias u-w='chmod u-w'
alias u-x='chmod u-x'
alias "u+"='chmod u+rwx'
alias u+r='chmod u+r'
alias u+w='chmod u+w'
alias u+x='chmod u+x'
alias ug-rwx='chmod ug-rwx'
alias ug+rwx='chmod ug+rwx'
alias upd='projekti-new update'
alias upl='synkronoi upl'
alias v=verkko
alias +w='chmod +w'
alias "w-"='chmod a-w'
alias "w+"='chmod a+w'
alias wh=which
alias without='bundle install --without'
alias +x='chmod +x'
alias x=exit
alias "x-"='chmod a-x'
alias "x+"='chmod a+x'
alias y='synkronoi ssh'
