alias ..='cd ..'
alias +a='chmod a+rwx'
alias a="git add -A; git commit -m"
alias "a-"='chmod a-rwx'
alias a-r='chmod a-r'
alias a-w='chmod a-w'
alias a-x='chmod a-x'
alias "a+"='chmod a+rwx'
alias a+r='chmod a+r'
alias a+w='chmod a+w'
alias a+x='chmod a+x'
alias add='git add'
alias b=bundle
alias bi='bundle install'
alias biw='bundle install --without'
alias branch='git branch'
alias bu=bundle
alias bx='bundle exec'
alias cd..='cd ..'
alias cim='git commit -m'
alias clone='git clone'
alias co='git checkout'
alias d=diff
alias dc=cd
alias e=echo
alias ed=muokkaa
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
alias +g='chmod g+rwx'
alias g=git
alias "g-"='chmod g-rwx'
alias g-r='chmod g-r'
alias g-w='chmod g-w'
alias g-x='chmod g-x'
alias "g+"='chmod g+rwx'
alias g+r='chmod g+r'
alias g+w='chmod g+w'
alias g+x='chmod g+x'
alias grep='grep --color'                     # show differences in colour
alias h=heroku
alias hst='cat ~/.bash_history'
alias k=kill
alias k80=kaiku80
alias k9='kill -9'
alias ker=kerain
alias l='ls -A'
alias la='ls -olA'
#alias levy='df -h'
alias l3='ls -la|less'
alias ll='ls -la'
alias llg='ls -la|grep'
alias lll='ls -la|less'
alias loki='GIT_PAGER=cat git log --pretty=oneline'
alias md=mkdir
alias merge='git merge'
alias migrate='rails db:migrate'
alias mk=make
alias more=less
alias n=nano
alias n2='nano -w -T 2'
alias +o='chmod o+rwx'
alias "o-"='chmod o-rwx'
alias o-r='chmod o-r'
alias o-w='chmod o-w'
alias o-x='chmod o-x'
alias "o+"='chmod o+rwx'
alias o+r='chmod o+r'
alias o+w='chmod o+w'
alias o+x='chmod o+x'
alias origin='git remote -v|grep origin'
alias p=projekti
alias psf='ps fu'
alias pull='git pull'
alias push='git push'
alias +r='chmod +r'
alias r=rails
alias "r-"='chmod a-r'
alias "r+"='chmod a+r'
alias rd=rmdir
alias remote='git remote'
alias reset='rails db:migrate:reset'
alias rollback='rails db:rollback'
alias routes='rails routes'
alias rl='screen -list'
alias ru=screen
alias rv='git remote -v'
alias s3=sqlite3
alias seed='rails db:seed'
alias srv='rails server'
alias st='if [ -d .git ]; then git status; else if [ -d ../.git ]; then git status; else if [ -d ../../.git ]; then git status; fi; fi; fi'
alias syn='synkronoi syn'
alias t=touch
alias tst='rails test'
alias +u='chmod u+rwx'
alias "u-"='chmod u-rwx'
alias u-r='chmod u-r'
alias u-w='chmod u-w'
alias u-x='chmod u-x'
alias "u+"='chmod u+rwx'
alias u+r='chmod u+r'
alias u+w='chmod u+w'
alias u+x='chmod u+x'
alias upd=projekti_update
alias upl='synkronoi upl'
alias v=verkko
alias +w='chmod +w'
alias "w-"='chmod a-w'
alias "w+"='chmod a+w'
alias +x='chmod +x'
alias x=exit
alias "x-"='chmod a-x'
alias "x+"='chmod a+x'
