#!/bin/bash

#summarize the status of git project in one line.
KR_PROJ_STATUS=$(git status)
KR_PROJ_BRANCH=$(echo $KR_PROJ_STATUS | \grep 'On branch')
case $KR_PROJ_BRANCH in
	*master*)
		KR_PROJ_UPDATE=$(echo $KR_PROJ_STATUS | \grep origin)
		case $KR_PROJ_UPDATE in
			*ahead*) echo "You are ahead of master branch in commits.";;
			*date*)
				KR_PROJ_COMMITS=$(echo $KR_PROJ_STATUS | \grep commit | \grep to)
				case $KR_PROJ_COMMITS in
					*nothing*) echo "Up-to-date with origin/master";;
					*) echo "You have changes not staged for commit.";;
				esac;;
		esac;;
	*) echo "Not in master branch";;
esac
